In [5]:
from collections import OrderedDict
VEHICLE_MODE_DICT = dict(
    #left=OrderedDict(dl=2, du=2, ud=2, ul=2),
    left  = OrderedDict(dl=0, du=0, ud=2, ul=0),
                         straight=OrderedDict(dl=1, du=2, ud=2, ru=2, ur=2),
                         right=OrderedDict(dr=1, ur=2, lr=2))

def dict2flat(inp):
    out = []
    for key, val in inp.items():
        out.extend([key]*val)
    return out

def dict2num(inp):
    out = 0
    for _, val in inp.items():
        out += val
    return out

VEH_NUM = dict(left=dict2num(VEHICLE_MODE_DICT['left']),
               straight=dict2num(VEHICLE_MODE_DICT['straight']),
               right=dict2num(VEHICLE_MODE_DICT['right']))

VEHICLE_MODE_LIST = dict(left=dict2flat(VEHICLE_MODE_DICT['left']),
                         straight=dict2flat(VEHICLE_MODE_DICT['straight']),
                         right=dict2flat(VEHICLE_MODE_DICT['right']))
VEHICLE_MODE_LIST

{'left': ['ud', 'ud'],
 'straight': ['dl', 'du', 'du', 'ud', 'ud', 'ru', 'ru', 'ur', 'ur'],
 'right': ['dr', 'ur', 'ur', 'lr', 'lr']}

In [6]:
VEH_NUM

{'left': 2, 'straight': 9, 'right': 5}

In [16]:
%matplotlib inline
import matplotlib.pyplot as plt

In [22]:
import numpy as np
np.stack([[1],[2],[3],[4]],0)

array([[1],
       [2],
       [3],
       [4]])

In [36]:

xs = np.array([i for i in range(100)])
reduced = np.arange(0, 100, 10)
xs_reduced = xs()


SyntaxError: invalid syntax (<ipython-input-36-1bc85eec3546>, line 3)

In [28]:
xs_tile = np.tile(np.reshape(xs, (-1, 1)), [1, 10])
xs_tile

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [48]:
x = np.array([i for i in range(100)])
y = np.array([i for i in range(100)])
xs = np.array([12])
ys = np.array([12])
path_len = 100
ratio = 10
reduced_idx = np.arange(0, path_len, ratio)
reduced_len = len(reduced_idx)
reduced_path_x, reduced_path_y = x[reduced_idx], y[reduced_idx]

xs_tile = np.tile(np.reshape(xs, (-1, 1)), [1, reduced_len])
ys_tile = np.tile(np.reshape(ys, (-1, 1)), [1, reduced_len])

pathx_tile = np.tile(np.reshape(reduced_path_x, (1, -1)), [len(xs), 1])
pathy_tile = np.tile(np.reshape(reduced_path_y, (1, -1)), [len(ys), 1])

dist_array = np.square(xs_tile - pathx_tile) + np.square(ys_tile - pathy_tile)

indexs = np.argmin(dist_array, 1) * ratio
indexs

array([10], dtype=int64)

In [50]:
dist_array

array([[  288,     8,   128,   648,  1568,  2888,  4608,  6728,  9248,
        12168]], dtype=int32)

In [58]:
np.concatenate((dist_array.squeeze()[:-2],np.array([1,1])),axis = 0)

array([ 288,    8,  128,  648, 1568, 2888, 4608, 6728,    1,    1])

In [59]:
dist_array.squeeze()[-2:]

array([ 9248, 12168], dtype=int32)

In [3]:
import numpy as np 
a = np.array([1, 1, 2])
a

array([1, 1, 2])

In [4]:
a[np.newaxis,:]

array([[1, 1, 2]])